presubmits:
  kubernetes-sigs/secrets-store-csi-driver:
  - name: pull-secrets-store-csi-driver-lint
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/secrets-store-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200326-e946722-master
        command:
        - runner.sh
        args:
        - make
        - test-style
    annotations:
      testgrid-dashboards: sig-auth-secrets-store-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-secrets-store-csi-driver-lint
      description: "Run linting rules for Secrets Store CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-secrets-store-csi-driver-unit
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/secrets-store-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200326-e946722-master
        command:
        - runner.sh
        args:
        - make
        - test
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-auth-secrets-store-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-secrets-store-csi-driver-unit
      description: "Run unit tests for Secrets Store CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-secrets-store-csi-driver-sanity
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/secrets-store-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200326-e946722-master
        command:
        - runner.sh
        args:
        - make
        - sanity-test
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-auth-secrets-store-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-secrets-store-csi-driver-sanity
      description: "Run sanity tests for Secrets Store CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-secrets-store-csi-driver-e2e-vault
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/secrets-store-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
      # this is required because we want to run kind in docker
      preset-dind-enabled: "true"
      # this is required to make CNI installation to succeed for kind
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200326-e946722-master
        command:
        - runner.sh
        args:
        - bash
        - -c
        - >-
          apt-get update && apt-get install bats && apt-get install gettext-base -y &&
          make e2e-bootstrap &&
          export KUBECONFIG=$(kind get kubeconfig-path) &&
          make e2e-vault
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-auth-secrets-store-csi-driver, provider-azure-presubmit
      testgrid-tab-name: pr-secrets-store-csi-driver-e2e-vault
      description: "Run e2e test with vault provider for Secrets Store CSI driver."
      testgrid-num-columns-recent: '30'

postsubmits:
  kubernetes-sigs/secrets-store-csi-driver:
  - name: secrets-store-csi-driver-e2e-vault-postsubmit
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/secrets-store-csi-driver
    branches:
    - master
    labels:
      preset-service-account: "true"
      # this is required because we want to run kind in docker
      preset-dind-enabled: "true"
      # this is required to make CNI installation to succeed for kind
      preset-kind-volume-mounts: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200326-e946722-master
        command:
        - runner.sh
        args:
        - bash
        - -c
        - >-
          apt-get update && apt-get install bats && apt-get install gettext-base -y &&
          make e2e-bootstrap &&
          export KUBECONFIG=$(kind get kubeconfig-path) &&
          make e2e-vault
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-auth-secrets-store-csi-driver
      testgrid-tab-name: secrets-store-csi-driver-e2e-vault-postsubmit
      description: "Run e2e test with vault provider for Secrets Store CSI driver postsubmit"
      testgrid-num-columns-recent: '30'
