test_groups:
# OpenShift Dedicated integration
- name: osd-int-4.2
  gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-osde2e-master-e2e-int-4.2
  column_header:
  - configuration_value: cluster-version
- name: osd-int-4.3
  gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-osde2e-master-e2e-int-4.3
  column_header:
  - configuration_value: cluster-version
- name: osd-int-4.4
  gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-osde2e-master-e2e-int-4.4
  column_header:
  - configuration_value: cluster-version
- name: osd-upgrade-int-4.2-4.2
  gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-osde2e-master-e2e-int-4.2-4.2
  column_header:
  - configuration_value: cluster-version
  - configuration_value: upgrade-version
- name: osd-upgrade-int-4.2-4.3
  gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-osde2e-master-e2e-int-4.2-4.3
  column_header:
  - configuration_value: cluster-version
  - configuration_value: upgrade-version
- name: osd-upgrade-int-4.3-4.3
  gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-osde2e-master-e2e-int-4.3-4.3
  column_header:
  - configuration_value: cluster-version
  - configuration_value: upgrade-version
- name: osd-upgrade-int-4.3-4.4
  gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-osde2e-master-e2e-int-4.3-4.4
  column_header:
  - configuration_value: cluster-version
  - configuration_value: upgrade-version

# OpenShift Dedicated staging
- name: osd-stage-default
  gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-osde2e-master-e2e-stage-default
  column_header:
  - configuration_value: cluster-version
- name: osd-stage-next
  gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-osde2e-master-e2e-stage-next
  column_header:
  - configuration_value: cluster-version
- name: osd-upgrade-stage-default-next
  gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-osde2e-master-e2e-stage-default-next
  column_header:
  - configuration_value: cluster-version
  - configuration_value: upgrade-version

# OpenShift Dedicated production
- name: osd-prod-default
  gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-osde2e-master-e2e-prod-default
  column_header:
  - configuration_value: cluster-version
- name: osd-prod-next
  gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-osde2e-master-e2e-prod-next
  column_header:
  - configuration_value: cluster-version
- name: osd-upgrade-prod-default-next
  gcs_prefix: origin-ci-test/logs/periodic-ci-openshift-osde2e-master-e2e-prod-default-next
  column_header:
  - configuration_value: cluster-version
  - configuration_value: upgrade-version

dashboards:
# OpenShift Dedicated integration dashboard
- name: redhat-osd-int
  dashboard_tab:
  - name: osd-int-4.2
    description: Runs cluster acceptance tests on an OpenShift Dedicated 4.2 integration cluster.
    test_group_name: osd-int-4.2
    base_options: width=10
    open_test_template: # The URL template to visit after clicking on a cell
      url: https://prow.svc.ci.openshift.org/view/gcs/<gcs_prefix>/<changelist>
    file_bug_template: # The URL template to visit when filing a bug
      url: https://github.com/openshift/osde2e/issues/new
      options:
        - key: title
          value: 'E2E: <test-name>'
        - key: body
          value: <test-url>
    open_bug_template: # The URL template to visit when visiting an associated bug
      url: https://github.com/openshift/osde2e/issues/
    results_url_template: # The URL template to visit after clicking
      url: https://prow.svc.ci.openshift.org/job-history/<gcs_prefix>
    code_search_path: github.com/openshift/osde2e/search # URL for regression search links.
    code_search_url_template: # The URL template to visit when searching for changelists
      url: https://github.com/openshift/osde2e/compare/<start-custom-0>...<end-custom-0>
  - name: osd-int-4.3
    description: Runs cluster acceptance tests on an OpenShift Dedicated 4.3 integration cluster.
    test_group_name: osd-int-4.3
    base_options: width=10
    open_test_template: # The URL template to visit after clicking on a cell
      url: https://prow.svc.ci.openshift.org/view/gcs/<gcs_prefix>/<changelist>
    file_bug_template: # The URL template to visit when filing a bug
      url: https://github.com/openshift/osde2e/issues/new
      options:
        - key: title
          value: 'E2E: <test-name>'
        - key: body
          value: <test-url>
    open_bug_template: # The URL template to visit when visiting an associated bug
      url: https://github.com/openshift/osde2e/issues/
    results_url_template: # The URL template to visit after clicking
      url: https://prow.svc.ci.openshift.org/job-history/<gcs_prefix>
    code_search_path: github.com/openshift/osde2e/search # URL for regression search links.
    code_search_url_template: # The URL template to visit when searching for changelists
      url: https://github.com/openshift/osde2e/compare/<start-custom-0>...<end-custom-0>
  - name: osd-int-4.4
    description: Runs cluster acceptance tests on an OpenShift Dedicated 4.4 integration cluster.
    test_group_name: osd-int-4.4
    base_options: width=10
    open_test_template: # The URL template to visit after clicking on a cell
      url: https://prow.svc.ci.openshift.org/view/gcs/<gcs_prefix>/<changelist>
    file_bug_template: # The URL template to visit when filing a bug
      url: https://github.com/openshift/osde2e/issues/new
      options:
        - key: title
          value: 'E2E: <test-name>'
        - key: body
          value: <test-url>
    open_bug_template: # The URL template to visit when visiting an associated bug
      url: https://github.com/openshift/osde2e/issues/
    results_url_template: # The URL template to visit after clicking
      url: https://prow.svc.ci.openshift.org/job-history/<gcs_prefix>
    code_search_path: github.com/openshift/osde2e/search # URL for regression search links.
    code_search_url_template: # The URL template to visit when searching for changelists
      url: https://github.com/openshift/osde2e/compare/<start-custom-0>...<end-custom-0>
  - name: osd-upgrade-int-4.2-4.2
    description: Runs upgrade tests between OpenShift Dedicated 4.2 and 4.2 in integration.
    test_group_name: osd-upgrade-int-4.2-4.2
    base_options: width=10
    open_test_template: # The URL template to visit after clicking on a cell
      url: https://prow.svc.ci.openshift.org/view/gcs/<gcs_prefix>/<changelist>
    file_bug_template: # The URL template to visit when filing a bug
      url: https://github.com/openshift/osde2e/issues/new
      options:
        - key: title
          value: 'E2E: <test-name>'
        - key: body
          value: <test-url>
    open_bug_template: # The URL template to visit when visiting an associated bug
      url: https://github.com/openshift/osde2e/issues/
    results_url_template: # The URL template to visit after clicking
      url: https://prow.svc.ci.openshift.org/job-history/<gcs_prefix>
    code_search_path: github.com/openshift/osde2e/search # URL for regression search links.
    code_search_url_template: # The URL template to visit when searching for changelists
      url: https://github.com/openshift/osde2e/compare/<start-custom-0>...<end-custom-0>
  - name: osd-upgrade-int-4.2-4.3
    description: Runs upgrade tests between OpenShift Dedicated 4.2 and 4.3 in integration.
    test_group_name: osd-upgrade-int-4.2-4.3
    base_options: width=10
    open_test_template: # The URL template to visit after clicking on a cell
      url: https://prow.svc.ci.openshift.org/view/gcs/<gcs_prefix>/<changelist>
    file_bug_template: # The URL template to visit when filing a bug
      url: https://github.com/openshift/osde2e/issues/new
      options:
        - key: title
          value: 'E2E: <test-name>'
        - key: body
          value: <test-url>
    open_bug_template: # The URL template to visit when visiting an associated bug
      url: https://github.com/openshift/osde2e/issues/
    results_url_template: # The URL template to visit after clicking
      url: https://prow.svc.ci.openshift.org/job-history/<gcs_prefix>
    code_search_path: github.com/openshift/osde2e/search # URL for regression search links.
    code_search_url_template: # The URL template to visit when searching for changelists
      url: https://github.com/openshift/osde2e/compare/<start-custom-0>...<end-custom-0>
  - name: osd-upgrade-int-4.3-4.3
    description: Runs upgrade tests between OpenShift Dedicated 4.3 and 4.3 in integration.
    test_group_name: osd-upgrade-int-4.3-4.3
    base_options: width=10
    open_test_template: # The URL template to visit after clicking on a cell
      url: https://prow.svc.ci.openshift.org/view/gcs/<gcs_prefix>/<changelist>
    file_bug_template: # The URL template to visit when filing a bug
      url: https://github.com/openshift/osde2e/issues/new
      options:
        - key: title
          value: 'E2E: <test-name>'
        - key: body
          value: <test-url>
    open_bug_template: # The URL template to visit when visiting an associated bug
      url: https://github.com/openshift/osde2e/issues/
    results_url_template: # The URL template to visit after clicking
      url: https://prow.svc.ci.openshift.org/job-history/<gcs_prefix>
    code_search_path: github.com/openshift/osde2e/search # URL for regression search links.
    code_search_url_template: # The URL template to visit when searching for changelists
      url: https://github.com/openshift/osde2e/compare/<start-custom-0>...<end-custom-0>
  - name: osd-upgrade-int-4.3-4.4
    description: Runs upgrade tests between OpenShift Dedicated 4.3 and 4.4 in integration.
    test_group_name: osd-upgrade-int-4.3-4.4
    base_options: width=10
    open_test_template: # The URL template to visit after clicking on a cell
      url: https://prow.svc.ci.openshift.org/view/gcs/<gcs_prefix>/<changelist>
    file_bug_template: # The URL template to visit when filing a bug
      url: https://github.com/openshift/osde2e/issues/new
      options:
        - key: title
          value: 'E2E: <test-name>'
        - key: body
          value: <test-url>
    open_bug_template: # The URL template to visit when visiting an associated bug
      url: https://github.com/openshift/osde2e/issues/
    results_url_template: # The URL template to visit after clicking
      url: https://prow.svc.ci.openshift.org/job-history/<gcs_prefix>
    code_search_path: github.com/openshift/osde2e/search # URL for regression search links.
    code_search_url_template: # The URL template to visit when searching for changelists
      url: https://github.com/openshift/osde2e/compare/<start-custom-0>...<end-custom-0>

# OpenShift Dedicated staging dashboard
- name: redhat-osd-stage
  dashboard_tab:
  - name: osd-stage-default
    description: Runs cluster acceptance tests on an OpenShift Dedicated staging cluster using the current default version.
    test_group_name: osd-stage-default
    base_options: width=10
    open_test_template: # The URL template to visit after clicking on a cell
      url: https://prow.svc.ci.openshift.org/view/gcs/<gcs_prefix>/<changelist>
    file_bug_template: # The URL template to visit when filing a bug
      url: https://github.com/openshift/osde2e/issues/new
      options:
        - key: title
          value: 'E2E: <test-name>'
        - key: body
          value: <test-url>
    open_bug_template: # The URL template to visit when visiting an associated bug
      url: https://github.com/openshift/osde2e/issues/
    results_url_template: # The URL template to visit after clicking
      url: https://prow.svc.ci.openshift.org/job-history/<gcs_prefix>
    code_search_path: github.com/openshift/osde2e/search # URL for regression search links.
    code_search_url_template: # The URL template to visit when searching for changelists
      url: https://github.com/openshift/osde2e/compare/<start-custom-0>...<end-custom-0>
  - name: osd-stage-next
    description: Runs cluster acceptance tests on an OpenShift Dedicated staging cluster using the latest version.
    test_group_name: osd-stage-next
    base_options: width=10
    open_test_template: # The URL template to visit after clicking on a cell
      url: https://prow.svc.ci.openshift.org/view/gcs/<gcs_prefix>/<changelist>
    file_bug_template: # The URL template to visit when filing a bug
      url: https://github.com/openshift/osde2e/issues/new
      options:
        - key: title
          value: 'E2E: <test-name>'
        - key: body
          value: <test-url>
    open_bug_template: # The URL template to visit when visiting an associated bug
      url: https://github.com/openshift/osde2e/issues/
    results_url_template: # The URL template to visit after clicking
      url: https://prow.svc.ci.openshift.org/job-history/<gcs_prefix>
    code_search_path: github.com/openshift/osde2e/search # URL for regression search links.
    code_search_url_template: # The URL template to visit when searching for changelists
      url: https://github.com/openshift/osde2e/compare/<start-custom-0>...<end-custom-0>
  - name: osd-upgrade-stage-default-next
    description: Runs upgrade tests between OpenShift Dedicated current default version and latest in staging.
    test_group_name: osd-upgrade-stage-default-next
    base_options: width=10
    open_test_template: # The URL template to visit after clicking on a cell
      url: https://prow.svc.ci.openshift.org/view/gcs/<gcs_prefix>/<changelist>
    file_bug_template: # The URL template to visit when filing a bug
      url: https://github.com/openshift/osde2e/issues/new
      options:
        - key: title
          value: 'E2E: <test-name>'
        - key: body
          value: <test-url>
    open_bug_template: # The URL template to visit when visiting an associated bug
      url: https://github.com/openshift/osde2e/issues/
    results_url_template: # The URL template to visit after clicking
      url: https://prow.svc.ci.openshift.org/job-history/<gcs_prefix>
    code_search_path: github.com/openshift/osde2e/search # URL for regression search links.
    code_search_url_template: # The URL template to visit when searching for changelists
      url: https://github.com/openshift/osde2e/compare/<start-custom-0>...<end-custom-0>

# OpenShift Dedicated production dashboard
- name: redhat-osd-prod
  dashboard_tab:
  - name: osd-prod-default
    description: Runs cluster acceptance tests on an OpenShift Dedicated production cluster using the current default version.
    test_group_name: osd-prod-default
    base_options: width=10
    open_test_template: # The URL template to visit after clicking on a cell
      url: https://prow.svc.ci.openshift.org/view/gcs/<gcs_prefix>/<changelist>
    file_bug_template: # The URL template to visit when filing a bug
      url: https://github.com/openshift/osde2e/issues/new
      options:
        - key: title
          value: 'E2E: <test-name>'
        - key: body
          value: <test-url>
    open_bug_template: # The URL template to visit when visiting an associated bug
      url: https://github.com/openshift/osde2e/issues/
    results_url_template: # The URL template to visit after clicking
      url: https://prow.svc.ci.openshift.org/job-history/<gcs_prefix>
    code_search_path: github.com/openshift/osde2e/search # URL for regression search links.
    code_search_url_template: # The URL template to visit when searching for changelists
      url: https://github.com/openshift/osde2e/compare/<start-custom-0>...<end-custom-0>
  - name: osd-prod-next
    description: Runs cluster acceptance tests on an OpenShift Dedicated production cluster using the latest version.
    test_group_name: osd-prod-next
    base_options: width=10
    open_test_template: # The URL template to visit after clicking on a cell
      url: https://prow.svc.ci.openshift.org/view/gcs/<gcs_prefix>/<changelist>
    file_bug_template: # The URL template to visit when filing a bug
      url: https://github.com/openshift/osde2e/issues/new
      options:
        - key: title
          value: 'E2E: <test-name>'
        - key: body
          value: <test-url>
    open_bug_template: # The URL template to visit when visiting an associated bug
      url: https://github.com/openshift/osde2e/issues/
    results_url_template: # The URL template to visit after clicking
      url: https://prow.svc.ci.openshift.org/job-history/<gcs_prefix>
    code_search_path: github.com/openshift/osde2e/search # URL for regression search links.
    code_search_url_template: # The URL template to visit when searching for changelists
      url: https://github.com/openshift/osde2e/compare/<start-custom-0>...<end-custom-0>
  - name: osd-upgrade-prod-default-next
    description: Runs upgrade tests between OpenShift Dedicated current default version and latest in production.
    test_group_name: osd-upgrade-prod-default-next
    base_options: width=10
    open_test_template: # The URL template to visit after clicking on a cell
      url: https://prow.svc.ci.openshift.org/view/gcs/<gcs_prefix>/<changelist>
    file_bug_template: # The URL template to visit when filing a bug
      url: https://github.com/openshift/osde2e/issues/new
      options:
        - key: title
          value: 'E2E: <test-name>'
        - key: body
          value: <test-url>
    open_bug_template: # The URL template to visit when visiting an associated bug
      url: https://github.com/openshift/osde2e/issues/
    results_url_template: # The URL template to visit after clicking
      url: https://prow.svc.ci.openshift.org/job-history/<gcs_prefix>
    code_search_path: github.com/openshift/osde2e/search # URL for regression search links.
    code_search_url_template: # The URL template to visit when searching for changelists
      url: https://github.com/openshift/osde2e/compare/<start-custom-0>...<end-custom-0>
