---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # Used by container image promotor audit jobs
    # TODO(fejta): better define these rules and enforce them in presubmit.
    iam.gke.io/gcp-service-account: k8s-infra-gcr-promoter@k8s-gcr-audit-test-prod.iam.gserviceaccount.com
  name: k8s-gcr-audit-test-prod
  namespace: test-pods
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # Used by Kops testing jobs
    iam.gke.io/gcp-service-account: pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com
  name: k8s-kops-test
  namespace: test-pods
---
# TODO(fejta): any other service accounts
