postsubmits:
  # this is the github repo we'll build from; this block needs to be repeated for each repo.
  kubernetes-sigs/cluster-api:
    - name: post-cluster-api-push-images
      cluster: test-infra-trusted
      annotations:
        # this is the name of some testgrid dashboard to report to.
        testgrid-dashboards: sig-cluster-lifecycle-image-pushes
      decorate: true
      branches:
        - ^master$
        - ^release-0.2$
        # this is a regex for semver, from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
        - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
      spec:
        serviceAccountName: deployer # TODO(fejta): use pusher
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20200213-0032cdb
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-cluster-api
              - --scratch-bucket=gs://k8s-staging-cluster-api-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
  kubernetes-sigs/cluster-api-provider-aws:
    - name: post-cluster-api-provider-aws-push-images
      cluster: test-infra-trusted
      annotations:
        # this is the name of some testgrid dashboard to report to.
        testgrid-dashboards: sig-cluster-lifecycle-image-pushes
      decorate: true
      branches:
        - ^master$
        - ^release-0.4$
        # this is a regex for semver, from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
        - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
      spec:
        serviceAccountName: deployer # TODO(fejta): use pusher
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20200213-0032cdb
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-cluster-api-aws
              - --scratch-bucket=gs://k8s-staging-cluster-api-aws-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
  kubernetes-sigs/cluster-api-provider-azure:
    - name: post-cluster-api-provider-azure-push-images
      cluster: test-infra-trusted
      annotations:
        testgrid-dashboards: sig-cluster-lifecycle-image-pushes, sig-cluster-lifecycle-cluster-api-provider-azure
        testgrid-alert-email: k8s-infra-staging-cluster-api-azure@kubernetes.io
      decorate: true
      branches:
        - ^master$
        - ^release-0.3$
        # this is a regex for semver, from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
        - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
      spec:
        serviceAccountName: deployer # TODO(fejta): use pusher
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20200213-0032cdb
            command:
              - /run.sh
            args:
              - --project=k8s-staging-cluster-api-azure
              - --scratch-bucket=gs://k8s-staging-cluster-api-azure-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
  kubernetes-sigs/cluster-api-provider-gcp:
    - name: post-cluster-api-provider-gcp-push-images
      cluster: test-infra-trusted
      annotations:
        # this is the name of some testgrid dashboard to report to.
        testgrid-dashboards: sig-cluster-lifecycle-image-pushes
      decorate: true
      branches:
        - ^master$
        - ^release-0.2$
        # this is a regex for semver, from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
        - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
      spec:
        serviceAccountName: deployer # TODO(fejta): use pusher
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20200213-0032cdb
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-cluster-api-gcp
              - --scratch-bucket=gs://k8s-staging-cluster-api-gcp-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
  kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm:
    - name: post-cluster-api-bootstrap-provider-push-images
      cluster: test-infra-trusted
      annotations:
        # this is the name of some testgrid dashboard to report to.
        testgrid-dashboards: sig-cluster-lifecycle-image-pushes
      decorate: true
      branches:
        - ^master$
        # this is a regex for semver, from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
        - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
      spec:
        serviceAccountName: deployer # TODO(fejta): use pusher
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20200213-0032cdb
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-capi-kubeadm
              - --scratch-bucket=gs://k8s-staging-capi-kubeadm-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
  kubernetes-sigs/cluster-api-provider-openstack:
    - name: post-cluster-api-provider-openstack-push-images
      cluster: test-infra-trusted
      annotations:
        # this is the name of some testgrid dashboard to report to.
        testgrid-dashboards: sig-cluster-lifecycle-image-pushes
      decorate: true
      branches:
        - ^master$
        - ^release-.+$
        # this is a regex for semver, from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
        - ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
      spec:
        serviceAccountName: deployer # TODO(fejta): use pusher
        containers:
          - image: gcr.io/k8s-testimages/image-builder:v20200213-0032cdb
            command:
              - /run.sh
            args:
              # this is the project GCB will run in, which is the same as the GCR images are pushed to.
              - --project=k8s-staging-capi-openstack
              - --scratch-bucket=gs://k8s-staging-capi-openstack-gcb
              - --env-passthrough=PULL_BASE_REF
              - .
