periodics:
- name: ci-cluster-api-provider-gcp-build
  interval: 1h
  decorate: true
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-gcp
    base_ref: master
    path_alias: "sigs.k8s.io/cluster-api-provider-gcp"
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200326-e946722-experimental
      command:
      - "runner.sh"
      - "./scripts/ci-build.sh"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp
    testgrid-tab-name: build
- name: ci-cluster-api-provider-gcp-test
  interval: 1h
  decorate: true
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-gcp
    base_ref: master
    path_alias: "sigs.k8s.io/cluster-api-provider-gcp"
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200326-e946722-experimental
      args:
      - "runner.sh"
      - "./scripts/ci-test.sh"
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp
    testgrid-tab-name: unit tests
- name: ci-cluster-api-provider-gcp-make-conformance-master
  interval: 3h
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  decorate: true
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-gcp
    base_ref: master
    path_alias: "sigs.k8s.io/cluster-api-provider-gcp"
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: master
    path_alias: "sigs.k8s.io/cluster-api"
  - org: kubernetes-sigs
    repo: image-builder
    base_ref: master
    path_alias: "sigs.k8s.io/image-builder"
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200326-e946722-experimental
        env:
          - name: "CAPI_BRANCH"
            value: "master"
          - name: "CABPK_BRANCH"
            value: "master"
          - name: "BOSKOS_HOST"
            value: "boskos.test-pods.svc.cluster.local"
        command:
          - "runner.sh"
          - "./scripts/ci-e2e.sh"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            # these are both a bit below peak usage during build
            # this is mostly for building kubernetes
            memory: "9000Mi"
            # during the tests more like 3-20m is used
            cpu: 2000m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp
    testgrid-tab-name: capg-conformance-master
    testgrid-alert-email: kubernetes-sig-cluster-lifecycle-cluster-api-alerts@googlegroups.com
    testgrid-num-failures-to-alert: "2"
- name: ci-cluster-api-provider-gcp-make-conformance-stable
  interval: 3h
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  decorate: true
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-gcp
    base_ref: release-0.2
    path_alias: "sigs.k8s.io/cluster-api-provider-gcp"
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: master
    path_alias: "sigs.k8s.io/cluster-api"
  - org: kubernetes-sigs
    repo: image-builder
    base_ref: master
    path_alias: "sigs.k8s.io/image-builder"
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200326-e946722-experimental
        env:
          - name: "CAPI_BRANCH"
            value: "stable"
          - name: "CABPK_BRANCH"
            value: "stable"
          - name: "BOSKOS_HOST"
            value: "boskos.test-pods.svc.cluster.local"
        command:
          - "runner.sh"
          - "./scripts/ci-e2e.sh"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            # these are both a bit below peak usage during build
            # this is mostly for building kubernetes
            memory: "9000Mi"
            # during the tests more like 3-20m is used
            cpu: 2000m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp
    testgrid-tab-name: capg-conformance-stable
    testgrid-alert-email: kubernetes-sig-cluster-lifecycle-cluster-api-alerts@googlegroups.com
    testgrid-num-failures-to-alert: "2"
- name: ci-cluster-api-provider-gcp-make-conformance-stable-k8s-ci-artifacts
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  decorate: true
  decoration_config:
    timeout: 3h
  interval: 4h
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-gcp
    base_ref: release-0.2
    path_alias: "sigs.k8s.io/cluster-api-provider-gcp"
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: master
    path_alias: "sigs.k8s.io/cluster-api"
  - org: kubernetes-sigs
    repo: image-builder
    base_ref: master
    path_alias: "sigs.k8s.io/image-builder"
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200326-e946722-experimental
        env:
          - name: "CAPI_BRANCH"
            value: "stable"
          - name: "CABPK_BRANCH"
            value: "stable"
          - name: "BOSKOS_HOST"
            value: "boskos.test-pods.svc.cluster.local"
        command:
          - "runner.sh"
          - "./scripts/ci-e2e.sh"
          - "--use-ci-artifacts"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            # these are both a bit below peak usage during build
            # this is mostly for building kubernetes
            memory: "9000Mi"
            # during the tests more like 3-20m is used
            cpu: 2000m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp, sig-release-master-informing
    testgrid-tab-name: capg-conformance-stable-k8s-master
    testgrid-alert-email: kubernetes-sig-cluster-lifecycle-cluster-api-alerts@googlegroups.com
    testgrid-num-failures-to-alert: "2"
