# To copy an image between projects:
# `gcloud compute --project <to-project> disks create <image name> --image=https://www.googleapis.com/compute/v1/projects/<from-project>/global/images/<image-name>`
# `gcloud compute --project <to-project> images create <image-name> --source-disk=<image-name>`
images:
  ubuntu:
    image: ubuntu-gke-1804-d1703-0-v20181113 # docker 17.03
    project: ubuntu-os-gke-cloud
  # see https://github.com/kubernetes/test-infra/issues/14465
  # coreos-beta:
  #   image: coreos-beta-1911-2-0-v20181024 # docker 18.06.1-ce
  #   project: coreos-cloud
  #   metadata: "user-data<test/e2e_node/jenkins/coreos-init.json"
  cos-stable1:
    image_regex: cos-stable-63-10032-71-0 # docker 17.03.2
    project: cos-cloud
    metadata: "user-data<test/e2e_node/jenkins/cos-init-live-restore.yaml,gci-update-strategy=update_disabled"
  cos-stable2:
    image_regex: cos-stable-60-9592-84-0 # docker 1.13.1
    project: cos-cloud
    metadata: "user-data<test/e2e_node/jenkins/cos-init-live-restore.yaml,gci-update-strategy=update_disabled"
