presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-integration
    always_run: true
    branches:
    # we migrated to podutils for v1.16+
    - release-1.15
    - release-1.14
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/bootstrap:v20200324-0132e79
        args:
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--timeout=60"
        - --scenario=kubernetes_verify
        - --
        - "--branch=${PULL_BASE_REF}"
        - --prow
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 4
  # this replaces the bootstrap / scenario based job going forward
  - name: pull-kubernetes-integration
    always_run: true
    decorate: true
    skip_branches:
    - release-\d+.\d+ # per-release job
    annotations:
      fork-per-release: "true"
      testgrid-num-failures-to-alert: '10'
      testgrid-alert-stale-results-hours: '24'
      testgrid-create-test-group: 'true'
    path_alias: k8s.io/kubernetes
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200326-e946722-master
        command:
        - runner.sh
        args:
        - ./hack/jenkins/test-dockerized.sh
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 4
  - name: pull-kubernetes-integration
    always_run: true
    decorate: true
    branches:
    - release-1.17 # per-release job
    path_alias: k8s.io/kubernetes
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200326-e946722-1.17
        command:
        - runner.sh
        args:
        - ./hack/jenkins/test-dockerized.sh
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 4
  - name: pull-kubernetes-integration
    always_run: true
    decorate: true
    branches:
    - release-1.16 # per-release job
    path_alias: k8s.io/kubernetes
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200326-e946722-1.16
        command:
        - runner.sh
        args:
        - ./hack/jenkins/test-dockerized.sh
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 4
periodics:
- interval: 1h
  name: ci-kubernetes-integration-master
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  annotations:
    fork-per-release: "true"
    fork-per-release-periodic-interval: 2h 2h 6h 24h
    fork-per-release-generic-suffix: "true"
    testgrid-dashboards: sig-release-master-blocking, google-unit
    testgrid-tab-name: integration-master
    testgrid-alert-email: kubernetes-release-team@googlegroups.com
    description: "Ends up running: make test-cmd test-integration"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20200326-e946722-master
      command:
      - runner.sh
      args:
      - ./hack/jenkins/test-dockerized.sh
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 4
