presubmits:
  kubernetes-sigs/cluster-api-provider-digitalocean:
  - name: pull-cluster-api-provider-digitalocean-test
    always_run: true
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200326-e946722-master
        command:
        - "./scripts/ci-test.sh"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: pr-test
  - name: pull-cluster-api-provider-digitalocean-build
    always_run: true
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200326-e946722-master
        command:
        - "./scripts/ci-build.sh"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: pr-build
  - name: pull-cluster-api-provider-digitalocean-verify
    always_run: true
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200326-e946722-master
        command:
        - make
        args:
        - verify
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: pr-verify
  - name: pull-cluster-api-provider-digitalocean-lint
    always_run: true
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    spec:
      containers:
      - image: golangci/golangci-lint:v1.21.0
        command:
        - make
        args:
        - lint
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: pr-lint
