presubmits:
  kubernetes/test-infra:
  - name: pull-test-infra-bazel-canary
    decorate: true
    skip_report: true
    always_run: true
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: launcher.gcr.io/google/bazel
        imagePullPolicy: Always
        env:
        - name: USE_BAZEL_VERSION
          value: real  # Ignore .bazelversion
        command:
        - hack/bazel.sh
        args:
        - test
        - --config=ci
        - --nobuild_tests_only
        - //...
    annotations:
      testgrid-dashboards: sig-testing-canaries, presubmits-test-infra
      testgrid-tab-name: test-infra-bazel-canary

# Testing to make sure things still update.
periodics:
- interval: 10m
  name: ci-test-infra-canary-echo-test
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
  annotations:
    testgrid-dashboards: sig-testing-canaries
    testgrid-tab-name: echo-test
    description: temporarily echoing things.
- name: ci-test-infra-benchmark-demo
  interval: 20m
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
    path_alias: k8s.io/test-infra
  spec:
    containers:
    - image: gcr.io/k8s-testimages/benchmarkjunit:latest
      command:
      - /benchmarkjunit
      args:
      - --log-file=$(ARTIFACTS)/benchmark-log.txt
      - --output=$(ARTIFACTS)/junit_benchmarks.xml
      - --pass-on-error
      - ./experiment/dummybenchmarks/...
  annotations:
    testgrid-alert-email: colew@google.com
    testgrid-dashboards: sig-testing-canaries
    testgrid-tab-name: benchmark-demo
    description: Demoing JUnit golang benchmark results.
