postsubmits:
  kubernetes/test-infra:
  - name: post-test-infra-bazel
    branches:
    - master
    decorate: true
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: launcher.gcr.io/google/bazel:2.0.0
        env:
        - name: USE_BAZEL_VERSION
          value: real  # Ignore .bazelversion
        command:
        - hack/bazel.sh
        args:
        - test
        - --config=ci
        - --nobuild_tests_only
        - //...
    annotations:
      testgrid-dashboards: sig-testing-misc
      testgrid-tab-name: post-bazel
      description: Runs bazel test //... on the test-infra repo on each commit
